apiVersion: apps/v1
kind: Deployment
metadata:
  name: commands-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commandservice
  template:
    metadata:
      labels:
        app: commandservice
    spec:
      containers:
        - name: commandservice
          image: olawaleusman01/commandservice:latest
          env:
            - name: ConnectionStrings__CommandCon
              value: Server=mssql-clusterip-srv,1433;Initial Catalog=CommandDb;User ID=sa;Password=Password1@;
---
apiVersion: v1
kind: Service
metadata:
  name: commandnpservice-srv
spec:
  type: NodePort
  selector:
    app: commandservice
  ports:
    - port: 80
      name: commandservice
      targetPort: 80
      nodePort: 30002
---
apiVersion: v1
kind: Service
metadata:
  name: command-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: commandservice
  ports:
    - port: 80
      name: commandservice
      targetPort: 80
